[package]
name = "serveros-pg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "serveros_pg"
path = "src/lib.rs"

[dependencies]
serveros-json = { path = "../json" }
serveros-crypto = { path = "../crypto" }
