//  AgentBootstrap.swift
//  ServerOS
//
//  Turning "I have a server" into "ServerOS manages this server".
//
//  ──────────────────────────────────────────────────────────────────────────
//  This is the highest-stakes flow in the product. It runs once per server,
//  over SSH, as root, on a machine the user cares about — and if it goes wrong
//  halfway the user needs to know exactly which half. So every step here is
//  named, is reported before it starts, and fails with a sentence about what
//  ServerOS was doing rather than with a shell error.
//
//  It is also the only part of the app that runs shell commands as a matter of
//  course. Everything afterwards is typed HTTP against the agent. The shell
//  usage here is bounded, auditable, and written out in full below rather than
//  assembled from fragments at runtime.
//  ──────────────────────────────────────────────────────────────────────────

import CryptoKit
import Foundation

// MARK: - Steps

/// Where setup has got to. The UI shows one of these at a time.
public enum BootstrapStep: Equatable, Sendable, CaseIterable {
    case testingConnection
    case installingKey
    case checkingRequirements
    case installingAgent
    case startingAgent
    case enrolling
    case verifying
    case done

    /// Present tense, no full stop: this is a label under a spinner, not a
    /// sentence in a paragraph.
    public var title: String {
        switch self {
        case .testingConnection:   return "Connecting to the server…"
        case .installingKey:       return "Installing the ServerOS key…"
        case .checkingRequirements: return "Checking what this server can do…"
        case .installingAgent:     return "Installing the ServerOS agent…"
        case .startingAgent:       return "Starting the agent…"
        case .enrolling:           return "Pairing this Mac with the server…"
        case .verifying:           return "Verifying the connection…"
        case .done:                return "Finishing setup…"
        }
    }

    /// The order the steps actually happen in, which is not the declaration
    /// order: enrollment has to write the agent's key *before* the agent is
    /// started, because the agent reads its secret once at boot and refuses to
    /// serve without one. A progress bar should count through this.
    public static let progressOrder: [BootstrapStep] = [
        .testingConnection,
        .installingKey,
        .checkingRequirements,
        .installingAgent,
        .enrolling,
        .startingAgent,
        .verifying,
        .done,
    ]
}

// MARK: - Results

/// What the agent printed at the end of enrollment.
///
/// The line is `SERVEROS-ENROLLMENT-V1 <server_id> <secret_b64> <port> <version>`
/// and it is generated by `serveros-agent enroll`. See
/// `agent/crates/agent/src/enroll.rs` — the two parsers have to agree, so the
/// rules below are copied from `Enrollment::parse_bundle` deliberately
/// literally, including the "at least 43 characters of secret" check.
public struct EnrollmentBundle: Equatable, Sendable {
    public let serverID: String
    /// The decoded 32-byte shared secret. Keychain-bound from here on.
    public let secret: Data
    /// The port the agent listens on, on the server's loopback.
    public let port: Int
    /// The agent's version, when the line carried one. Older agents omit it.
    public let agentVersion: String?

    public init(serverID: String, secret: Data, port: Int, agentVersion: String?) {
        self.serverID = serverID
        self.secret = secret
        self.port = port
        self.agentVersion = agentVersion
    }
}

/// What ServerOS learned about the server before installing anything.
public struct SystemProbe: Equatable, Sendable {
    public let systemName: String       // "Linux"
    public let machine: String          // "x86_64", "aarch64"
    public let kernel: String           // "6.8.0-40-generic"
    public let distributionID: String?  // "ubuntu"
    public let prettyName: String?      // "Ubuntu 24.04.1 LTS"
    public let versionID: String?       // "24.04"

    public var isLinux: Bool {
        systemName.caseInsensitiveCompare("Linux") == .orderedSame
    }

    /// Distributions the agent is built and tested against.
    public static let knownDistributions: Set<String> = [
        "ubuntu", "debian", "raspbian", "linuxmint", "pop",
        "rhel", "centos", "rocky", "almalinux", "fedora", "amzn", "ol",
        "opensuse-leap", "opensuse-tumbleweed", "sles",
        "arch", "alpine",
    ]

    public var isKnownDistribution: Bool {
        guard let distributionID else { return false }
        return SystemProbe.knownDistributions.contains(distributionID.lowercased())
    }

    /// Parse the output of `uname -s; uname -m; uname -r; cat /etc/os-release`.
    ///
    /// Pure, so the interesting cases — a Mac, a BSD, a distro with no
    /// `/etc/os-release` — can be tested without a server.
    public static func parse(_ output: String) -> SystemProbe? {
        let lines = output
            .split(whereSeparator: { $0.isNewline })
            .map { String($0).trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }

        guard lines.count >= 2 else { return nil }

        let systemName = lines[0]
        let machine = lines[1]
        let kernel = lines.count >= 3 && !lines[2].contains("=") ? lines[2] : ""

        var fields: [String: String] = [:]
        for line in lines.dropFirst(2) {
            guard let separator = line.firstIndex(of: "=") else { continue }
            let key = String(line[line.startIndex..<separator])
            var value = String(line[line.index(after: separator)...])
            if value.hasPrefix("\""), value.hasSuffix("\""), value.count >= 2 {
                value = String(value.dropFirst().dropLast())
            }
            fields[key] = value
        }

        return SystemProbe(
            systemName: systemName,
            machine: machine,
            kernel: kernel,
            distributionID: fields["ID"],
            prettyName: fields["PRETTY_NAME"] ?? fields["NAME"],
            versionID: fields["VERSION_ID"]
        )
    }
}

/// Everything the Add Server flow needs to write a `ServerRecord` and a
/// `ServerCredential`.
public struct BootstrapResult: Sendable {
    public let serverID: String
    /// 32 bytes. Goes straight to the Keychain and nowhere else.
    public let agentSecret: Data
    public let agentPort: Int
    /// The host key as `"<algorithm> <base64>"`, for pinning.
    public let hostKey: String
    /// The same key as `"SHA256:…"`, for showing a person.
    public let hostKeyFingerprint: String
    /// Always `nil` today. The agent's `/v1/system` is the only honest source
    /// of a `SystemInfo`, and reaching it means opening the tunnel and making
    /// an authenticated request — which is the caller's job, not this type's.
    /// See `probe` for what setup itself learned.
    public let system: SystemInfo?
    /// What `uname` and `/etc/os-release` said.
    public let probe: SystemProbe
    /// The key ServerOS generated and installed, if it generated one. Belongs
    /// in the Keychain with the secret.
    public let generatedKeyPair: ServerOSKeyPair?
    public let agentVersion: String?
    /// Non-fatal things worth telling the user afterwards.
    public let warnings: [String]
}

// MARK: - Options

/// How the agent should be installed. Defaults are what the Add Server flow
/// uses; the fields exist so tests and enterprise builds can vary it.
public struct InstallOptions: Sendable {

    /// Which agent build to install. Only meaningful when downloading.
    public var agentVersion: String = "latest"

    /// Where the agent comes from.
    ///
    /// `.bundled` is the default and needs no network on the server at all:
    /// ServerOS ships the Linux agent and pushes it down the SSH connection it
    /// already holds. That matters — plenty of servers worth managing have no
    /// outbound internet, and a setup flow that silently assumes one is a setup
    /// flow that fails in front of the user.
    public enum BinarySource: Sendable, Equatable {
        /// A build carried inside the app, matched to the server's `uname -m`.
        case bundled
        /// A specific file on this Mac. For developers running an agent they
        /// just compiled.
        case file(URL)
        /// Let the installer fetch it. For organisations mirroring the agent
        /// on their own host; the URL must be one they control.
        case download(baseURL: String)
    }
    public var binary: BinarySource = .bundled

    /// Which systemd hardening profile the unit gets.
    public enum Profile: String, Sendable {
        /// `ProtectSystem=strict`, no capabilities. Read-only management works;
        /// anything that writes outside the agent's own directories does not.
        case hardened
        /// Adds a documented drop-in that lets the agent manage users, files
        /// and services. Choose this knowingly.
        case manage
    }
    public var profile: Profile = .hardened

    /// Where the installer script comes from. `.contents` exists so tests do
    /// not need an app bundle.
    public enum ScriptSource: Sendable {
        case bundled
        case contents(String)
    }
    public var script: ScriptSource = .bundled

    /// Passed through to the script verbatim, after the options above.
    public var extraArguments: [String] = []

    public init() {}
}

// MARK: - The flow

/// Installs, enrolls and starts the agent on one server.
public actor AgentBootstrap {

    /// Where the installer puts things. Shared with `install-agent.sh`; if one
    /// changes, the other must.
    public static let agentBinaryPath = "/usr/local/bin/serveros-agent"
    public static let agentConfigPath = "/etc/serveros/agent.json"
    public static let serviceName = "serveros-agent"

    private let client: SSHClient
    private let options: InstallOptions
    private let progress: @Sendable (BootstrapStep) -> Void

    public init(
        client: SSHClient,
        options: InstallOptions = InstallOptions(),
        progress: @Sendable @escaping (BootstrapStep) -> Void
    ) {
        self.client = client
        self.options = options
        self.progress = progress
    }

    // MARK: Run

    /// Replace the agent on a server that already has one, and restart it.
    ///
    /// Everything `run` does except the parts that only make sense once:
    /// no host-key confirmation, no key installation, no enrolment. The
    /// server keeps its identity and its shared secret, so the Mac's stored
    /// credential stays valid across the upgrade.
    ///
    /// Needed because the agent is installed from a copy carried inside the
    /// app, which means a fix to the agent reaches a server only when the app
    /// puts it there. Without this, a server set up last month is frozen on
    /// whatever the agent was that day.
    public func upgradeAgent() async throws -> InstallOutcome {
        progress(.testingConnection)
        try await client.connect()

        progress(.checkingRequirements)
        let requirements = try await checkRequirements()

        progress(.installingAgent)
        let outcome = try await installAgent(requirements: requirements)

        progress(.startingAgent)
        try await startAgent(
            requirements: requirements,
            hasSystemd: outcome.initSystem == "systemd"
        )

        // Wait for it to *answer*, not merely to have been started. The first
        // version of this returned here, and the app reconnected into the gap
        // between "systemd forked the process" and "the process bound its
        // socket" — which reaches the user as "ServerOS couldn't reach the
        // agent", moments after an upgrade that actually worked.
        progress(.verifying)
        try await waitUntilServing(requirements: requirements)

        progress(.done)
        return outcome
    }

    /// Upgrade only if the server isn't already running this exact binary.
    ///
    /// Compares checksums rather than version strings. A version number is a
    /// promise a developer has to remember to keep; a SHA-256 is what is
    /// actually on the disk. Two builds of the same version differ here, which
    /// is precisely the case that matters — an agent fixed between releases
    /// reaches a server only when the app notices the difference.
    ///
    /// Returns nil when nothing needed doing, so the caller can tell "already
    /// current" from "upgraded" without guessing.
    @discardableResult
    public func upgradeAgentIfNeeded() async throws -> InstallOutcome? {
        if try await installedAgentIsCurrent() { return nil }
        return try await upgradeAgent()
    }

    /// Whether the agent on the server is byte-for-byte the one this copy of
    /// ServerOS carries.
    public func installedAgentIsCurrent() async throws -> Bool {
        try await client.connect()

        // Only the bundled source can be compared: `.download` means the
        // binary isn't here to hash, and `.file` is a developer pointing at a
        // build on purpose. Neither should be turned into a surprise upgrade.
        guard case .bundled = options.binary else { return true }

        let requirements = try await checkRequirements()
        guard let localURL = AgentBinary.bundled(for: requirements.architecture),
              let data = try? Data(contentsOf: localURL) else {
            return true
        }
        let expected = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()

        let remote = try await client.run(
            "sha256sum \(Shell.quote(Self.agentBinaryPath)) 2>/dev/null | cut -d' ' -f1",
            timeout: 60
        )
        let actual = remote.stdout.trimmingCharacters(in: .whitespacesAndNewlines)

        // No answer means no sha256sum, no binary, or no permission to look.
        // Reinstalling is the safe reading of "I can't tell": it is idempotent,
        // and the alternative is leaving a server on an agent that may be the
        // reason the user is here.
        guard !actual.isEmpty else { return false }
        return actual == expected
    }

    public func run(installKey: ServerOSKeyPair?) async throws -> BootstrapResult {
        var warnings: [String] = []

        // 1. Is this a Linux box, and which one?
        progress(.testingConnection)
        try await client.connect()
        let probe = try await probeSystem()

        guard probe.isLinux else {
            throw ServerOSError.serverIsNotLinux(probe.systemName)
        }
        if !probe.isKnownDistribution {
            // Not fatal. The agent is a static binary and systemd is systemd;
            // an unknown ID is usually a derivative distribution.
            warnings.append(
                "ServerOS hasn't been tested on \(probe.prettyName ?? probe.distributionID ?? "this distribution"). Setup will continue."
            )
        }

        // 2. Install our own key, so ServerOS never needs the password again.
        if let installKey {
            progress(.installingKey)
            try await installAuthorizedKey(installKey)
        }

        // 3. What can we do here?
        progress(.checkingRequirements)
        let requirements = try await checkRequirements()

        // 4. Put the agent on the machine, but do not start it yet.
        progress(.installingAgent)
        let install = try await installAgent(requirements: requirements)

        // 5. Enrollment writes /etc/serveros/agent.key. This HAS to happen
        //    before the agent starts: the agent loads its secret once, at
        //    startup, and exits 78 if there isn't one.
        progress(.enrolling)
        let bundle = try await enroll(requirements: requirements)

        // 6. Now start it — or restart it, if an older instance was already
        //    running with the key we just replaced.
        progress(.startingAgent)
        try await startAgent(requirements: requirements, hasSystemd: install.initSystem == "systemd")

        // 7. Locally: is the service up? Everything beyond that — opening the
        //    tunnel, calling /v1/health with a signed request — belongs to the
        //    caller, which owns the agent client and the credential store. It
        //    is the caller's verification that decides whether setup "worked",
        //    so this step deliberately stops at "the process is running".
        progress(.verifying)
        if let warning = try await verifyRunning(requirements: requirements, hasSystemd: install.initSystem == "systemd") {
            warnings.append(warning)
        }

        progress(.done)

        guard let hostKey = await client.observedHostKey else {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.verifying.title,
                reason: "ServerOS didn't record this server's host key.",
                technical: nil
            )
        }

        let observedFingerprint = await client.observedHostKeyFingerprint
        let fingerprint = observedFingerprint
            ?? SSHFingerprint.sha256(ofOpenSSHPublicKey: hostKey)
            ?? hostKey

        return BootstrapResult(
            serverID: bundle.serverID,
            agentSecret: bundle.secret,
            agentPort: bundle.port,
            hostKey: hostKey,
            hostKeyFingerprint: fingerprint,
            system: nil,
            probe: probe,
            generatedKeyPair: installKey,
            agentVersion: bundle.agentVersion ?? install.version,
            warnings: warnings
        )
    }

    // MARK: Step 1 — the system

    func probeSystem() async throws -> SystemProbe {
        let command = "uname -s && uname -m && uname -r && (cat /etc/os-release 2>/dev/null || true)"
        let result = try await client.run(command, timeout: 30)

        guard result.succeeded, let probe = SystemProbe.parse(result.stdout) else {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.testingConnection.title,
                reason: "ServerOS couldn't work out what kind of machine this is.",
                causes: [
                    "The account may be restricted to a limited shell",
                    "The connection may have dropped mid-command",
                ],
                technical: result.stderr.isEmpty ? result.stdout : result.stderr
            )
        }
        return probe
    }

    // MARK: Step 2 — the key

    func installAuthorizedKey(_ keyPair: ServerOSKeyPair) async throws {
        let line = keyPair.publicKeyAuthorizedKeysLine
        let quoted = Shell.quote(line)

        // `grep -qxF` first so re-running setup doesn't add the same line
        // twice, and `umask 077` so the file is never briefly world-readable.
        // sshd silently ignores an authorized_keys file with loose permissions,
        // which is the single most common reason "key auth doesn't work".
        let script = """
        set -e
        umask 077
        mkdir -p "$HOME/.ssh"
        chmod 700 "$HOME/.ssh"
        touch "$HOME/.ssh/authorized_keys"
        chmod 600 "$HOME/.ssh/authorized_keys"
        if grep -qxF \(quoted) "$HOME/.ssh/authorized_keys"; then
            echo SERVEROS-KEY-ALREADY-PRESENT
        else
            printf '%s\\n' \(quoted) >> "$HOME/.ssh/authorized_keys"
            echo SERVEROS-KEY-INSTALLED
        fi
        """

        let result = try await client.run(script, timeout: 30)
        guard result.succeeded else {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.installingKey.title,
                reason: "ServerOS couldn't add its key to this account's authorized_keys.",
                causes: [
                    "The home directory may be read-only",
                    "The account's disk quota may be full",
                ],
                technical: result.stderr.isEmpty ? result.stdout : result.stderr
            )
        }
    }

    // MARK: Step 3 — requirements

    struct Requirements: Sendable {
        let uid: Int
        let hasSudo: Bool
        let hasSystemd: Bool
        let existingAgentVersion: String?
        /// `uname -m`, normalised. Decides which agent build gets uploaded, so
        /// a wrong answer here is a binary that will not run.
        let architecture: String

        var isRoot: Bool { uid == 0 }
        /// Prefix for a command that needs root. `-n` because ServerOS will not
        /// put a password on a command line where `ps` can read it.
        var privileged: String { isRoot ? "" : "sudo -n " }
    }

    func checkRequirements() async throws -> Requirements {
        let script = """
        echo "uid=$(id -u)"
        echo "arch=$(uname -m)"
        if command -v sudo >/dev/null 2>&1; then echo "sudo=yes"; else echo "sudo=no"; fi
        if command -v systemctl >/dev/null 2>&1; then echo "systemd=yes"; else echo "systemd=no"; fi
        if [ -x \(Self.agentBinaryPath) ]; then
            echo "agent=$(\(Self.agentBinaryPath) version 2>/dev/null || echo unknown)"
        else
            echo "agent="
        fi
        """

        let result = try await client.run(script, timeout: 30)
        guard result.succeeded else {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.checkingRequirements.title,
                reason: "ServerOS couldn't check what this server has installed.",
                technical: result.stderr.isEmpty ? result.stdout : result.stderr
            )
        }

        let fields = Self.labelledFields(result.stdout)
        let requirements = Requirements(
            uid: Int(fields["uid"] ?? "") ?? -1,
            hasSudo: fields["sudo"] == "yes",
            hasSystemd: fields["systemd"] == "yes",
            existingAgentVersion: (fields["agent"]?.isEmpty ?? true) ? nil : fields["agent"],
            architecture: AgentBinary.normalise(fields["arch"] ?? "")
        )

        guard requirements.uid >= 0 else {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.checkingRequirements.title,
                reason: "ServerOS couldn't tell which account it is connected as.",
                technical: result.stdout
            )
        }

        if !requirements.isRoot {
            guard requirements.hasSudo else { throw ServerOSError.sudoUnavailable }

            // Passwordless is required, checked here rather than discovered
            // three commands later.
            let sudoCheck = try await client.run("sudo -n true 2>&1", timeout: 20)
            guard sudoCheck.succeeded else {
                throw ServerOSError.sudoNeedsPassword
            }
        }

        return requirements
    }

    // MARK: Step 4 — the agent

    /// Public because `upgradeAgent` returns it, and a public method cannot
    /// hand back a type the rest of the module is not allowed to name.
    public struct InstallOutcome: Sendable {
        public let version: String?
        public let architecture: String?
        public let initSystem: String?
    }

    func installAgent(requirements: Requirements) async throws -> InstallOutcome {
        // Put the binary on the server first, so that by the time the installer
        // runs there is nothing left for it to fetch. Returns the remote path,
        // or nil when the caller asked for a download instead.
        let uploadedBinary = try await placeBinary(requirements: requirements)

        let script = try InstallScript.load(options.script)
        let encoded = Data(script.utf8).base64EncodedString()

        guard encoded.count < 200_000 else {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.installingAgent.title,
                reason: "The installer script is too large to upload in one command.",
                technical: "\(encoded.count) base64 characters"
            )
        }

        // The script is piped through base64 in a single `run()` rather than
        // copied with SFTP. That avoids requiring the sftp subsystem (which
        // hardened servers often disable), avoids a second protocol in this
        // layer entirely, and keeps the transfer inside the one authenticated
        // SSH session we already have. It is only sound for small, known
        // payloads — the size guard above is the boundary of that claim.
        let remotePath = "/tmp/serveros-install-\(UUID().uuidString.prefix(8)).sh"
        let arguments = installerArguments(requirements: requirements, binaryPath: uploadedBinary)

        // Deliberately not `set -e`: the installer's exit status has to survive
        // the clean-up, and `set -e` would skip the `rm` on failure and leave
        // the script sitting in /tmp.
        let command = """
        umask 077
        printf '%s' \(Shell.quote(encoded)) | base64 -d > \(remotePath) || exit 91
        chmod 700 \(remotePath) || exit 92
        \(requirements.privileged)/bin/sh \(remotePath) \(arguments)
        status=$?
        rm -f \(remotePath)
        exit $status
        """

        let result = try await client.run(command, timeout: 600)

        guard result.succeeded else {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.installingAgent.title,
                reason: "The ServerOS agent couldn't be installed on this server.",
                causes: Self.installCauses(for: options.binary, path: uploadedBinary),
                technical: Self.lastLines(result.stderr.isEmpty ? result.stdout : result.stderr, count: 20)
            )
        }

        // Best-effort: the installer copies the binary into place, so the
        // upload in /tmp is dead weight afterwards. Failure here is not worth
        // reporting — a stale file in /tmp is not a failed setup.
        if let uploadedBinary {
            _ = try? await client.run("rm -f \(Shell.quote(uploadedBinary))", timeout: 20)
        }

        return Self.parseInstallOutcome(result.stdout)
    }

    /// What could have gone wrong, given how the binary was meant to arrive.
    /// Listing download causes for an upload — or the reverse — sends the user
    /// looking in a place the failure cannot be.
    static func installCauses(for source: InstallOptions.BinarySource, path: String?) -> [String] {
        if path != nil {
            return [
                "There may not be enough free space in /usr/local or /tmp",
                "The account may not be allowed to write to /usr/local/bin",
                "The server may be a different architecture than the agent that was uploaded",
            ]
        }
        if case .download(let base) = source {
            return [
                "The server may not be able to reach \(base)",
                "There may not be enough free space in /usr/local",
                "curl or wget may not be installed",
            ]
        }
        return ["There may not be enough free space in /usr/local"]
    }

    func installerArguments(requirements: Requirements, binaryPath: String?) -> String {
        Self.installerArguments(options: options, requirements: requirements, binaryPath: binaryPath)
    }

    /// Static so it can be tested without standing up an SSH connection — the
    /// argument list is pure function of the options and what was uploaded, and
    /// it is the thing most likely to be got wrong in a hurry.
    static func installerArguments(
        options: InstallOptions,
        requirements: Requirements,
        binaryPath: String?
    ) -> String {
        var parts: [String] = []

        if let binaryPath {
            parts += ["--binary", Shell.quote(binaryPath)]
        } else if case .download(let base) = options.binary {
            parts += [
                "--version", Shell.quote(options.agentVersion),
                "--base-url", Shell.quote(base),
            ]
        }

        parts += [
            "--profile", Shell.quote(options.profile.rawValue),
            "--no-start",
        ]
        parts.append(contentsOf: options.extraArguments.map(Shell.quote))
        return parts.joined(separator: " ")
    }

    /// `SERVEROS-INSTALL-OK <version> <arch> <init>` is the only thing the
    /// installer is allowed to put on stdout.
    static func parseInstallOutcome(_ output: String) -> InstallOutcome {
        for line in output.split(whereSeparator: { $0.isNewline }) {
            let fields = line.split(whereSeparator: { $0.isWhitespace })
            guard fields.count >= 4, fields[0] == "SERVEROS-INSTALL-OK" else { continue }
            return InstallOutcome(
                version: String(fields[1]),
                architecture: String(fields[2]),
                initSystem: String(fields[3])
            )
        }
        return InstallOutcome(version: nil, architecture: nil, initSystem: nil)
    }

    // MARK: Getting the binary onto the server

    /// Uploads the agent and returns where it landed, or nil when the installer
    /// is expected to download it instead.
    func placeBinary(requirements: Requirements) async throws -> String? {
        let localURL: URL
        switch options.binary {
        case .download:
            return nil

        case .file(let url):
            localURL = url

        case .bundled:
            guard let found = AgentBinary.bundled(for: requirements.architecture) else {
                throw ServerOSError.agentBuildUnavailable(
                    architecture: requirements.architecture,
                    available: AgentBinary.bundledArchitectures()
                )
            }
            localURL = found
        }

        let data: Data
        do {
            data = try Data(contentsOf: localURL)
        } catch {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.installingAgent.title,
                reason: "ServerOS couldn't read the agent it was going to install.",
                causes: ["The file may have been moved or deleted: \(localURL.lastPathComponent)"],
                technical: error.localizedDescription
            )
        }

        let remotePath = "/tmp/serveros-agent-\(UUID().uuidString.prefix(8))"
        try await upload(data, to: remotePath, step: BootstrapStep.installingAgent.title)
        return remotePath
    }

    /// Streams a file over the SSH session already open, and verifies what
    /// arrived.
    ///
    /// The payload goes on **stdin**, in one channel. The first version of this
    /// put base64 in the command string and sent it in 37 chunks; an SSH exec
    /// request is a single packet with a negotiated ceiling, 48 KiB of base64
    /// sailed past it, and setup died with
    /// `NIOSSHError.protocolViolation: Sent EOF out of sequence` — one stray
    /// EOF taking down the whole SSH connection. Data belongs on stdin.
    ///
    /// Still `run()` rather than SFTP, for the reason the installer script is
    /// sent this way too: hardened servers routinely disable the sftp
    /// subsystem, and this needs no second protocol and no second
    /// authentication.
    func upload(_ data: Data, to remotePath: String, step: String) async throws {
        let encoded = Data(data.base64EncodedString().utf8)

        // `base64 -d` is in coreutils on every supported distribution; the
        // capability probe has already established this is Linux.
        let write = """
        umask 077
        base64 -d > \(Shell.quote(remotePath)) || exit 91
        chmod 0700 \(Shell.quote(remotePath)) || exit 92
        """

        let written: SSHCommandResult
        do {
            written = try await client.run(write, stdin: encoded, timeout: 600)
        } catch {
            throw ServerOSError.setupFailed(
                step: step,
                reason: "ServerOS couldn't copy the agent to the server.",
                causes: [
                    "The connection may have dropped part-way through",
                    "The server may be out of space in /tmp",
                ],
                technical: "\(error)"
            )
        }

        guard written.succeeded else {
            _ = try? await client.run("rm -f \(Shell.quote(remotePath))", timeout: 20)
            throw ServerOSError.setupFailed(
                step: step,
                reason: "ServerOS couldn't copy the agent to the server.",
                causes: [
                    "The server may be out of space in /tmp",
                    "base64 may not be installed on this server",
                ],
                technical: Self.lastLines(
                    written.stderr.isEmpty ? written.stdout : written.stderr, count: 10)
            )
        }

        // Prove byte-for-byte that what is on the server is what left this Mac.
        // A truncated upload produces a binary that either fails to run or,
        // worse, runs wrongly — neither acceptable for something about to be
        // installed as a privileged service.
        let expected = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        let verify = """
        if command -v sha256sum >/dev/null 2>&1; then
            echo "sha=$(sha256sum \(Shell.quote(remotePath)) | cut -d' ' -f1)"
        elif command -v shasum >/dev/null 2>&1; then
            echo "sha=$(shasum -a 256 \(Shell.quote(remotePath)) | cut -d' ' -f1)"
        else
            echo "sha="
        fi
        echo "bytes=$(wc -c < \(Shell.quote(remotePath)) | tr -d ' ')"
        """

        let result = try await client.run(verify, timeout: 120)
        let fields = Self.labelledFields(result.stdout)

        guard result.succeeded, fields["bytes"] == String(data.count) else {
            _ = try? await client.run("rm -f \(Shell.quote(remotePath))", timeout: 20)
            throw ServerOSError.setupFailed(
                step: step,
                reason: "The agent didn't arrive on the server intact.",
                causes: [
                    "The connection may have dropped part-way through",
                    "The server may be out of space in /tmp",
                ],
                technical: "expected \(data.count) bytes, got \(fields["bytes"] ?? "nothing")"
            )
        }

        // No sha256sum on the server is a thinner guarantee than a checksum,
        // but the byte count above still held, so this is not nothing.
        if let actual = fields["sha"], !actual.isEmpty, actual != expected {
            _ = try? await client.run("rm -f \(Shell.quote(remotePath))", timeout: 20)
            throw ServerOSError.setupFailed(
                step: step,
                reason: "The agent didn't arrive on the server intact.",
                causes: ["The upload was corrupted in transit"],
                technical: "sha256 expected \(expected.prefix(16))…, got \(actual.prefix(16))…"
            )
        }
    }

    // MARK: Step 5 — enrollment

    func enroll(requirements: Requirements) async throws -> EnrollmentBundle {
        // `--force` because setup is also how a server is re-paired: the app
        // may have lost its Keychain item, or the user may be moving the
        // server to another Mac. Rotating the secret is the safe direction —
        // it disconnects any Mac holding the old one, which is exactly what
        // "set this server up again" should mean.
        let command = "\(requirements.privileged)\(Self.agentBinaryPath) enroll --force"
        let result = try await client.run(command, timeout: 120)

        // Both streams: a login shell's MOTD, a sudo lecture and a package
        // manager's "restart required" notice all land in here, which is why
        // the bundle line is prefixed and scanned for rather than read off the
        // last line.
        guard let bundle = Self.parseEnrollmentBundle(result.stdout + "\n" + result.stderr) else {
            throw ServerOSError.enrollmentBundleNotFound(
                technical: Self.lastLines(result.stdout + "\n" + result.stderr, count: 20)
            )
        }
        return bundle
    }

    /// Find the enrollment bundle in a pile of SSH session output.
    ///
    /// Pure and static so it can be tested with realistic noise and without a
    /// server. The rules match `Enrollment::parse_bundle` in the agent exactly:
    /// whitespace-separated fields, the prefix must be the whole first field,
    /// the port must fit in a `u16`, the secret must be at least 43 characters
    /// (32 bytes, base64url, unpadded), and the version field is optional so a
    /// line from an older agent still parses.
    public static func parseEnrollmentBundle(_ output: String) -> EnrollmentBundle? {
        for line in output.split(whereSeparator: { $0.isNewline }) {
            let fields = line.split(whereSeparator: { $0.isWhitespace }).map(String.init)
            guard fields.count >= 4, fields[0] == enrollmentPrefix else { continue }

            let serverID = fields[1]
            let secretText = fields[2]
            guard !serverID.isEmpty, secretText.count >= 43 else { continue }
            guard let port = UInt16(fields[3]) else { continue }
            guard let secret = Base64URL.decode(secretText), secret.count >= 16 else { continue }

            let version: String? = fields.count >= 5 ? fields[4] : nil
            return EnrollmentBundle(
                serverID: serverID,
                secret: secret,
                port: Int(port),
                agentVersion: version
            )
        }
        return nil
    }

    public static let enrollmentPrefix = "SERVEROS-ENROLLMENT-V1"

    // MARK: Step 6 — starting

    func startAgent(requirements: Requirements, hasSystemd: Bool) async throws {
        let command: String
        if hasSystemd || requirements.hasSystemd {
            // `enable` then `restart` rather than `enable --now`: an agent left
            // running from a previous install is holding the secret we have
            // just replaced, and only a restart makes it read the new one.
            command = """
            \(requirements.privileged)systemctl enable \(Self.serviceName) >/dev/null 2>&1
            \(requirements.privileged)systemctl restart \(Self.serviceName)
            """
        } else {
            command = "\(requirements.privileged)/etc/init.d/\(Self.serviceName) restart"
        }

        let result = try await client.run(command, timeout: 120)
        guard result.succeeded else {
            let logs = try? await client.run(
                "\(requirements.privileged)journalctl -u \(Self.serviceName) -n 30 --no-pager 2>&1 || true",
                timeout: 30
            )
            throw ServerOSError.setupFailed(
                step: BootstrapStep.startingAgent.title,
                reason: "The ServerOS agent wouldn't start.",
                causes: [
                    "Another process may already be using port 8723",
                    "The agent may not have permission to write /var/lib/serveros",
                ],
                technical: Self.lastLines(
                    (result.stderr.isEmpty ? result.stdout : result.stderr) + "\n" + (logs?.stdout ?? ""),
                    count: 30
                )
            )
        }
    }

    // MARK: Readiness

    /// A shell script that waits until the agent answers its own health check.
    ///
    /// `systemctl is-active` says "active" the instant the process is forked.
    /// Between that and the socket being bound there is a window — small on an
    /// idle box, not small on a busy one — and anything that connects during it
    /// gets `connection refused`. Every restart in this app used to be followed
    /// immediately by an attempt to talk to the agent, so that window was
    /// reachable by users, and it read as "the agent is down" rather than "wait
    /// half a second".
    ///
    /// `serveros-agent status` is the right probe because it is the agent's own
    /// binary asking the agent over its Unix socket, exiting 0 only on a real
    /// `200` from `/v1/health`. Nothing extra has to be installed, and the loop
    /// runs on the server rather than as a dozen SSH round-trips.
    static func waitUntilServingScript(privileged: String, attempts: Int = 20) -> String {
        """
        i=0
        while [ $i -lt \(attempts) ]; do
            if \(privileged)\(agentBinaryPath) status >/dev/null 2>&1; then
                echo "serving=yes"
                exit 0
            fi
            i=$((i+1))
            sleep 1
        done
        echo "serving=no"
        \(privileged)journalctl -u \(serviceName) -n 20 --no-pager 2>/dev/null | tail -n 8
        exit 93
        """
    }

    /// Block until the agent is answering, or fail with what the journal said.
    func waitUntilServing(requirements: Requirements) async throws {
        let script = Self.waitUntilServingScript(privileged: requirements.privileged)
        let result = try await client.run(script, timeout: 120)
        guard result.succeeded, result.stdout.contains("serving=yes") else {
            throw ServerOSError.setupFailed(
                step: BootstrapStep.verifying.title,
                reason: "The agent started but never answered.",
                causes: [
                    "It may be failing on startup and being restarted in a loop",
                    "Its configuration may be invalid — the log below usually says so",
                ],
                technical: Self.lastLines(result.stdout + result.stderr, count: 12)
            )
        }
    }

    // MARK: Step 7 — local verification

    /// `nil` when the agent is running, a warning when it is starting but has
    /// not finished, and a thrown error when it is definitely not running.
    func verifyRunning(requirements: Requirements, hasSystemd: Bool) async throws -> String? {
        // Ask whether it is *answering*, not whether systemd started it. This
        // used to check `is-active` three times over a second and a half, which
        // is both the wrong question and not long enough: "active" is true from
        // the moment the process is forked, and a busy server takes longer than
        // that to bind a socket. `serveros-agent status` works on every init
        // system, because it goes to the agent's own Unix socket.
        let probe = try await client.run(
            Self.waitUntilServingScript(privileged: requirements.privileged),
            timeout: 120
        )
        if probe.succeeded, probe.stdout.contains("serving=yes") { return nil }

        // Not answering yet. "Still coming up" is not the same as "failed", and
        // the caller is about to try the tunnel regardless, so a warning serves
        // the user better than refusing a setup that is about to work.
        if hasSystemd || requirements.hasSystemd {
            let state = try await client.run(
                "\(requirements.privileged)systemctl is-active \(Self.serviceName) 2>&1 || true",
                timeout: 30
            )
            if state.trimmedStdout.lowercased().hasPrefix("activating") {
                return "The agent was still starting when setup finished. If this server doesn't connect, try Reconnect in a moment."
            }
        }

        throw ServerOSError.setupFailed(
            step: BootstrapStep.verifying.title,
            reason: "The agent was installed but isn't answering.",
            causes: [
                "It may have failed on startup — the log below usually says why",
                "Its configuration may be invalid",
                "The server may be out of disk space",
            ],
            technical: Self.lastLines(probe.stdout + probe.stderr, count: 20)
        )
    }

    // MARK: Small helpers

    /// `key=value` lines, as emitted by the requirements script.
    static func labelledFields(_ output: String) -> [String: String] {
        var fields: [String: String] = [:]
        for line in output.split(whereSeparator: { $0.isNewline }) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard let separator = trimmed.firstIndex(of: "=") else { continue }
            let key = String(trimmed[trimmed.startIndex..<separator])
            let value = String(trimmed[trimmed.index(after: separator)...])
            fields[key] = value.trimmingCharacters(in: .whitespaces)
        }
        return fields
    }

    /// The tail of a command's output, for the "Technical details" disclosure.
    /// Whole logs do not belong in an error.
    static func lastLines(_ text: String, count: Int) -> String {
        let lines = text.split(whereSeparator: { $0.isNewline })
        return lines.suffix(count).joined(separator: "\n")
    }
}

// MARK: - Shell quoting

/// Turning a Swift string into one shell word.
enum Shell {
    /// Single quotes, with the one escape single quotes need. Every value that
    /// reaches a remote shell goes through here — a key comment can contain an
    /// apostrophe ("Orion's MacBook"), and a path can contain a space.
    static func quote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}

// MARK: - base64url

/// The agent encodes its secret with URL-safe, unpadded base64
/// (`serveros_crypto::b64url_encode`), which `Data(base64Encoded:)` will not
/// touch. Thirteen lines is cheaper than a dependency.
enum Base64URL {
    static func decode(_ text: String) -> Data? {
        var standard = text
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        while standard.count % 4 != 0 {
            standard.append("=")
        }
        return Data(base64Encoded: standard)
    }

    static func encode(_ data: Data) -> String {
        data.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }
}

// MARK: - The installer script

/// Finds `install-agent.sh`.
///
/// The script is a resource rather than a string literal in this file for two
/// reasons: a 200-line shell script embedded in Swift is unreviewable and
/// unlintable, and keeping it as a file means it can be run by hand against a
/// test VM, which is how it gets debugged.
enum InstallScript {

    /// Anchors `Bundle(for:)` to whichever bundle this code was compiled into.
    private final class Anchor {}

    static func load(_ source: InstallOptions.ScriptSource) throws -> String {
        switch source {
        case .contents(let text):
            return text
        case .bundled:
            // Prefer the file on disk: it is the source of truth, and a
            // developer testing a change to the installer expects the edited
            // script to be the one that runs. Fall back to the compiled-in
            // copy so a resource that failed to be bundled cannot strand a
            // user halfway through adding a server.
            if let url = bundledURL(), let text = try? String(contentsOf: url, encoding: .utf8) {
                return text
            }
            return embedded
        }
    }

    /// Looks in the bundle this code lives in, then the app bundle, then any
    /// resource bundle sitting beside them — which is where SwiftPM puts
    /// resources. `Bundle.module` is deliberately not referenced: it only
    /// exists when the target is built by SwiftPM *with* declared resources,
    /// and naming it would stop this file compiling anywhere else.
    static func bundledURL() -> URL? {
        let candidates = [Bundle(for: Anchor.self), Bundle.main]

        for bundle in candidates {
            if let url = bundle.url(forResource: "install-agent", withExtension: "sh") {
                return url
            }
        }

        for bundle in candidates {
            let container = bundle.bundleURL.deletingLastPathComponent()
            guard let entries = try? FileManager.default.contentsOfDirectory(
                at: container,
                includingPropertiesForKeys: nil
            ) else { continue }

            for entry in entries where entry.pathExtension == "bundle" {
                if let nested = Bundle(url: entry),
                   let url = nested.url(forResource: "install-agent", withExtension: "sh") {
                    return url
                }
            }
        }

        return nil
    }
}
